---
components:
  - name: bmp280
    description: |
      Driver for BMP280/BME280 digital pressure sensor
    group: pressure
    groups:
      - temperature
    code_owners:
      - name: UncleRus
    depneds:
      - name: i2cdev
      - name: log
      - name: esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: MIT
    copyrights:
      - name: UncleRus
        year: 2018
      - name: sheinz
        year: 2016
